from pathlib import Path

PYTHON_AGENT_HOST = "127.0.0.1"   # Python PC IP: 192.168.56.1 # Localhost: 127.0.0.1
PYTHON_AGENT_PORT = 5005
PYTHON_AGENT_FILE_PORT = 5006

LOCAL_GH_AGENT_HOST = "127.0.0.1"
LOCAL_GH_AGENT_PORT = 6005

HEADER_SIZE = 8
BUFFER_SIZE = 1024 * 1024
FILE_CHUNK_SIZE = 1024 * 1024

GH_AGENT_NAME = "Grasshopper Agent"
GH_AGENT_VERSION = "0.1.0"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCAL_RECEIVED_ROOT = PROJECT_ROOT / "GH_AGENT_RECEIVED"
LOG_DIR = LOCAL_RECEIVED_ROOT / "logs"
GH_AGENT_LOG_FILE = LOG_DIR / "gh_agent.log"

RECEIVED_ROOT = PROJECT_ROOT / "DATA_RECEIVED"

POLL_INTERVAL_SEC = 1.0